version: '3.9'
services:
  ssh.cyrhades.com:
    build: ssh
  webssh.cyrhades.com:
    build: webssh
    ports:
    - "80:8888"
  snake.cyrhades.com:
    image: anssi/fcsc2021-misc-snake:latest
    read_only: true
    ports:
      - "4000:4000"
